### PR TITLE
Add playlist of the "Learning Mathematics with Lean (2022)" event

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by Kha** [comment]
Could you please clean up the git history?

**Comment by pitmonticone** [comment]
> Could you please clean up the git history?

I've squashed all the commits I was allowed to squashed.

**Comment by pitmonticone** [comment]
@Kha I can just re-fork the repository and add the new commit. Would it be fine?

**Comment by Kha** [comment]
I've squashed them during merge now, but for the record, you do not need to refork the repo in order to rebase a PR branch

**Comment by pitmonticone** [comment]
Thanks a lot @Kha.

**Pull request merged**
