### PR TITLE
point CC publication to arxiv

### PR DESCRIPTION
**Pull request by dselsam**
Warning: I don't know how to run my own version to sanity check it but this change seems innocuous.

### CODE REVIEW

**Comment by leodemoura** [comment]
What is the motivation for this change?

**Comment by dselsam** [comment]
I was recently informed by someone whom I would be inclined to believe that it is a "faux pas" for an organization to have links to self-hosted PDFs for academic papers. Also, the paper below it points to its arxiv version, so it seemed like it was already our policy to do so for papers that are on the arxiv. Finally, doing this prevents any future broken-link issue like the one we just had.

I was just trying to be helpful and I don't feel strongly about it. No problem if you prefer to keep the old link and close the PR, for whatever reason.

**Comment by leodemoura** [comment]
Thanks for sending the pull request, but I will not merge it.
The broken link has been fixed.
I don't see the point of storing one paper at arxiv and the other ones here.
Moreover, I'm not willing to create an entry at arxiv for every paper we write.

**Comment by dselsam** [comment]
Okay. 

> I don't see the point of storing one paper at arxiv and the other ones here.

It doesn't matter to me but in case you missed this: the publication below, "Elaboration in Dependent Type Theory", points to its arxiv version.

**Pull request closed without merging**
